Repository jypjms/StockMilestone, pull requests merged in 2023-07, with the labels that each got.

#21 fix : 응답 구조 수정
  stock-milestone/src/main/java/fisa/stockmilestone/modules/global/ControllerAdvice.java
Labels: backend

#23 feat.follow
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/domain/Account.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/domain/Follow.java
Labels: backend, feature

#25 Feat.social login
  stock-milestone/build.gradle
  stock-milestone/src/main/java/fisa/stockmilestone/config/InitDb.java
  stock-milestone/src/main/java/fisa/stockmilestone/config/RestTemplateConfig.java
  stock-milestone/src/main/java/fisa/stockmilestone/config/WebConfig.java
  stock-milestone/src/main/java/fisa/stockmilestone/infra/oauth/client/GoogleOAuthClient.java
  stock-milestone/src/main/java/fisa/stockmilestone/infra/oauth/dto/GoogleTokenResponse.java
  stock-milestone/src/main/java/fisa/stockmilestone/infra/oauth/endpoint/GoogleOAuthEndPoint.java
  stock-milestone/src/main/java/fisa/stockmilestone/infra/oauth/support/JwtProvider.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/controller/AuthController.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/domain/Account.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/domain/Profile.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/domain/SocialType.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/OAuthAccount.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/TokenRequest.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/TokenResponse.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/repository/AccountRepository.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/service/AccountService.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/service/AuthService.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/global/ControllerAdvice.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/global/response/BaseException.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/global/response/BaseResponse.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/global/response/BaseResponseStatus.java
  stock-milestone/src/main/resources/application.yml
  stock-milestone/src/test/java/fisa/stockmilestone/modules/account/domain/AccountTest.java
  stock-milestone/src/test/java/fisa/stockmilestone/modules/account/repository/AccountRepositoryTest.java
  stock-milestone/src/test/java/fisa/stockmilestone/modules/account/service/AuthServiceTest.java
Labels: backend, feature

#27 refactor.dto
  stock-milestone/src/main/java/fisa/stockmilestone/StockMilestoneApplication.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/domain/Account.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/domain/Follow.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/GetFollowingRes.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/OAuthAccount.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/PostFollowReq.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/TokenRequest.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/account/dto/TokenResponse.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/controller/CommentController.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/domain/Comment.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/domain/Post.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/dto/GetCommentRes.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/dto/GetPostRes.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/dto/PatchCommentReq.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/dto/PatchPostReq.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/dto/PostCommentReq.java
  stock-milestone/src/main/java/fisa/stockmilestone/modules/board/dto/PostPostReq.java
  stock-milestone/src/main/resources/application.yml
Labels: enhancement, backend

#28 feat.connectS3
  stock-milestone/build.gradle
  stock-milestone/src/main/java/fisa/stockmilestone/FileUploadController.java
  stock-milestone/src/main/java/fisa/stockmilestone/config/StorageConfig.java
  stock-milestone/src/main/resources/application.yml
Labels: backend, feature
